### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by bigman212** [Themis404/completed_tasks#1]
Well done! c:
Мне почти не к чему придраться :p 
1) ``` a = int(input("Enter А ")) b = int(input("Enter В "))```
Программа небольшая, но всё равно не стоит забывать о том что переменные лучше называть понятно. Что такое А, что такое Б? Назови их лучше first_number (переменные в Питоне называются с маленькой буквы и через нижнее подчеркивание), second_number. 
2) def используется для создания функций. Пока это не стоит трогать. Убери def calculator(), и просто используй условие без def.

**Comment by Themis404** [comment]
но я по заданию делала, где было нужно написать функцию 
https://pythonworld.ru/osnovy/tasks.html

**Comment by bigman212** [comment]
А еще в задании написано что сначала надо пройти самоучитель :) 
Как только разберешь написание отдельных функций (i.e. main или тот же calculate), можно уже писать программы с функциями. А так можно просто сплошным текстом без страшных слов типа def или class. Пройди пока тот http://pythontutor.ru/

**Comment by Themis404** [comment]
:ь

**Comment by Themis404** [comment]
я на него и опиралась, когда не знала как делать

**Comment by bigman212** [comment]
Умничка. Просто выкидывай всё что там делаешь сюда, в репозиторий с отдельным файлом,  и я тоже это буду проверять.

**Comment by Themis404** [comment]
хорошо, пойду дальше
