### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by bigman212** [Themis404/completed_tasks#2]
С опозданием, но всё же. Сразу к делу.
1) Все задачи (файлы) переименуй. В стиле (task_one...task_three...). Чтобы было видно какое задание каким ты выполняла. К примеру Task_7 бессмыслен, т.к. я не вижу тут Task_6, или Task_4. Без разницы где ты взяла задания, просто именуй их по порядку выполнения. 
2) Программы тестировала?
3) Заметил что в two (снова плохое название, см п.1) два задания в одном. Ну, это не совсем плохо, но разбей их на функции что ли. Второе задание - одна функция, третье задание - другая. И еще main. И как надо. (Не забывай вынести функции за main во всех остальных файлах)
Теперь о самом вкусном - принципе единственности ответственности. [https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8](url). Вообще он относится к классам, но в функциях его тоже можно использовать. Принцип прост - у функции, или о класса, должна быть одна ответственность (функциональность) и всё. 
Теперь к местам где этот твой принцип нарушается. 
4)  `def time_in_the_degrees(hours, minutes, seconds, hour_all, min_all, sec_all, half_day):` 
Что делает эта функция? Выводит время? Возвращает время? Может меняет его? Если возвращает: то get_time_in_degrees (the убирают всегда, это не английский). Если выводит: print_time_in_degrees. Выглядит же лучше, ну?
Потом большое кол-во параметров. Аж 7. Может можно исправить? Что делает твоя функция?
**Вычисляет** минуты, часы, потом еще **выводит** время **и** **определяет** полдень или нет. 
Разбей всё на маленькие функции с одной обязанностью. Одна функция вычисляет градус, другая определяет полдень/нет, и т.д. 
Так же нужно сделать и во всех остальных файлах. Это называется рефакторинг. 
5) Привыкай использовать return вместо того чтобы просто выводить. Твой результат (например те же градусы) может использоваться в другом месте. Если не понятно зачем так делать - пиши, объясню. 
А так очень неплохо. Горжусь тобой.

**Comment by Themis404** [comment]
![58486a72849cf46a2a931338](https://user-images.githubusercontent.com/36556726/36535484-8bda17e8-1815-11e8-9172-f0e185ab2221.png)

**Comment by Themis404** [comment]
завтра рили все сделаю
kmplz
